### ISSUE TITLE
error on npm start

### ISSUE THREAD

**Issue by jonwolds** [mayeaux/generate-subtitles#11]
Hi,

I tried installing on Linux and on Windows, and both times I got the same error:
> init@0.0.0 start
> node app.js

G:\PyEnvs\whisp\generate-subtitles\node_modules\which\lib\index.js:106
  throw getNotFoundError(cmd)
  ^

Error: not found: yt-dlp
    at getNotFoundError (G:\PyEnvs\whisp\generate-subtitles\node_modules\which\lib\index.js:16:17)
    at AsyncFunction.whichSync [as sync] (G:\PyEnvs\whisp\generate-subtitles\node_modules\which\lib\index.js:106:9)
    at Object.<anonymous> (G:\PyEnvs\whisp\generate-subtitles\download.js:9:31)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (G:\PyEnvs\whisp\generate-subtitles\routes\index.js:7:31) {
  code: 'ENOENT'
}

I don't know my way around Node.js very well, so apologies if I've made a stupid mistake. I used the freesubtitles.ai server and I thought it was excellent!

Cheers,

Jon

**Comment by mayeaux** [comment]
Nope it's my fault for not having it in the docs, let me add it one sec

**Comment by mayeaux** [comment]
Sorry about that, I forgot about `yt-dlp` because the functionality isn't finished being implemented yet, check the README now it should have the solution for you
