### ISSUE TITLE
Error npm start

### ISSUE THREAD

**Issue by bidbiz** [mayeaux/generate-subtitles#58]
> init@0.0.0 start /root/generate-subtitles
> node app.js

maxConcurrentJobs
node env
development
FILES PASSWORD: undefined
{ nodeEnv: 'development' }
{ uploadLimitInMB: 3000 }
/root/generate-subtitles/node_modules/which/lib/index.js:111
  throw getNotFoundError(cmd)
  ^

Error: not found: ffprobe
    at getNotFoundError (/root/generate-subtitles/node_modules/which/lib/index.js:16:17)
    at AsyncFunction.whichSync [as sync] (/root/generate-subtitles/node_modules/which/lib/index.js:111:9)
    at Object.<anonymous> (/root/generate-subtitles/routes/transcribe.js:10:27)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/root/generate-subtitles/app.js:53:20) {
  code: 'ENOENT'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! init@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the init@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-22T00_22_20_603Z-debug.log

**Comment by bidbiz** [comment]
Fixed
