### ISSUE TITLE
Has libreTranslate been fully implemented?

### ISSUE THREAD

**Issue by 6monkeyrs** [mayeaux/generate-subtitles#59]
I have a need to parse my data locally, and would be interested to know if the libreTranslateWrapper is fully impletement. 

I have successfully installed libreTranslate instance locally and test some English to other languages.

**Comment by 6monkeyrs** [comment]
When I enable libreTranslate, i get the following error with no code:

Error: Not Found
    at C:\generate-subtitles\app.js:123:13
    at Layer.handle [as handle_request] (C:\generate-subtitles\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\generate-subtitles\node_modules\express\lib\router\index.js:328:13)
    at C:\generate-subtitles\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\generate-subtitles\node_modules\express\lib\router\index.js:346:12)
    at next (C:\generate-subtitles\node_modules\express\lib\router\index.js:280:10)
    at C:\generate-subtitles\node_modules\express\lib\router\index.js:646:15
    at next (C:\generate-subtitles\node_modules\express\lib\router\index.js:265:14)
    at Function.handle (C:\generate-subtitles\node_modules\express\lib\router\index.js:175:3)
    at router (C:\generate-subtitles\node_modules\express\lib\router\index.js:47:12) {
  status: 404
}
